defmodule ForestSurvey.Repo.Migrations.InitialSurveysDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vendors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :team, :text
      add :email, :text
      add :whatsapp, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:survey_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :tally_base_url, :text, null: false
      add :min_recontact_months, :bigint, null: false, default: 6

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:generated_links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :full_url, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :sent_at, :utc_datetime_usec
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :vendor_id,
          references(:vendors,
            column: :id,
            name: "generated_links_vendor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :client_id, :uuid, null: false
    end

    create table(:clients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:generated_links) do
      modify :client_id,
             references(:clients,
               column: :id,
               name: "generated_links_client_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:clients) do
      add :name, :text, null: false
      add :zone, :text
      add :main_contact, :text
      add :whatsapp, :text
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:clients) do
      remove :updated_at
      remove :inserted_at
      remove :active
      remove :whatsapp
      remove :main_contact
      remove :zone
      remove :name
    end

    drop constraint(:generated_links, "generated_links_client_id_fkey")

    alter table(:generated_links) do
      modify :client_id, :uuid
    end

    drop table(:clients)

    drop constraint(:generated_links, "generated_links_vendor_id_fkey")

    drop table(:generated_links)

    drop table(:survey_configs)

    drop table(:vendors)
  end
end
