defmodule ForestSurvey.Repo.Migrations.AddConfigName do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:survey_configs) do
      add :name, :text, default: "General", null: false
    end
  end

  def down do
    alter table(:survey_configs) do
      remove :name
    end
  end
end
